### ISSUE TITLE
Importación de censo mediante archivos csv

### ISSUE THREAD

**Issue by chainwarden16** [decide-ganimedes-censo/decide-ganimedes-censo#1]
Con el fin de agilizar la importación de censos, se podría añadir funcionalidad para leer archivos en formato .csv. Sería necesario comprobar que el formato del archivo sea válido, los datos introducidos son correctos (por ejemplo, que donde se espera una edad no se pueda introducir una cadena de sólo letras), y luego se deberán mostrar por pantalla.

Una tabla con un ID y los datos correspondientes podría ser útil y una forma ordenada de mostrar el contenido del censo.

**Comment by UtrillaJC** [comment]
Hasta que @chainwarden16 implemente el template de la página principal he creado un botón temporal en addCustomCensus que llama a la URL http://localhost:8000/census/importCensus y a la que se le pasa el fichero CSV.

Pendiente de qué @Iriabow verifique su correcto funcionamiento.

**Comment by Iriabow** [comment]
Funciona correctamente.
