### ISSUE TITLE
Testing de las nuevas funcionalidades implementadas

### ISSUE THREAD

**Issue by UtrillaJC** [decide-ganimedes-censo/decide-ganimedes-censo#13]
Por cada nueva funcionalidad que se implemente, crearemos los test unitarios correspondientes para comprobar el correcto funcionamiento.

**Comment by davidromesp** [comment]
Con este commit 7da7ec654f6c9d8f2325aedf27515cfe50dac176 , ya estarían testeadas las funcionalidades de addAllRegistered y de addAllByCity(positivamente y negativamente)

Aún faltarían las de addAllBySex, addAllByAge y addCustomCensus, y seguramente alguno más

**Comment by davidromesp** [comment]
He creado un  nuevo issue para el test de addAllBySex, con prioridad alta.

**Comment by Iriabow** [comment]
Vale, puede ser útil subdividir los test que quedan por issues cierro esta issue entonces.
