### ISSUE TITLE
Creación de censos mediante un filtrado personalizado

### ISSUE THREAD

**Issue by UtrillaJC** [decide-ganimedes-censo/decide-ganimedes-censo#14]
Se requiere la creación de un filtro múltiple a la hora de crear un censo para simplificar las labores de asignación de personas a un determinada votación utilizando varios atributos (por edad, por sexo, ...).

**Comment by Iriabow** [comment]
No se puede añadir el censo si la votación no está iniciada, deberías quitar esa restricción, en todo caso, lo que se debería hacer es impedir que se modifique el censo una vez iniciada la votación, tiene más sentido. 
Lo dejamos para una issue general.

**Comment by UtrillaJC** [comment]
Ahora mismo controla que el proceso de censado sea cuando se haya iniciado la votación, ¿no tendría más sentido así?

**Comment by Iriabow** [comment]
Yo diría que no, es decir lo normal es tener un registro de quien va a votar antes de que se produzca la votación. Por ejemplo, el caso de la elecciones de un país.

**Comment by Iriabow** [comment]
Revisado, funciona correctamente.

**Comment by UtrillaJC** [comment]
![image](https://user-images.githubusercontent.com/9322398/50763012-e9d0f980-126e-11e9-8e7c-cda89bfdfac5.png)

He visto que falta por añadir la internacionalización del contenido. Además, he encontrado un error en el que al introducir dos fechas en el rango de edad, no avanza.

**Comment by Iriabow** [comment]
La internacionalización no forma parte de está funcionalidad, que es a lo que se refiere el issue. Respecto a lo de introducir dos fechas, como ya ha sido cerrada la issue; crea una nueva issue con etiqueta bug para ello. Cierro de nuevo la issue.

**Comment by UtrillaJC** [comment]
Lección aprendida.
