### ISSUE TITLE
Creación de filtrados personalizados.

### ISSUE THREAD

**Issue by Iriabow** [decide-ganimedes-censo/decide-ganimedes-censo#15]
Se requiere la creación de un filtro múltiple a la hora  de crear un censo, simplificando las labores de asignación de personas a  un determinado censo por varios atributos (por edad, por sexo, ...).

Esto va asociado a la issue #14 .

**Comment by UtrillaJC** [comment]
Para mayor claridad se ha añadido todo el desarrollo de este issue en el issue #14
