### ISSUE TITLE
Automatización de Docker en Linux

### ISSUE THREAD

**Issue by UtrillaJC** [decide-ganimedes-censo/decide-ganimedes-censo#16]
Creación de un script de Docker para automatizar la construcción, configuración y despliegue de Docker. Para ello se pueden implementar varias opciones: listado de imágenes y despliegue mediante docker-compose, etc.

Además se incluirá un readme.txt explicando su funcionamiento.

**Comment by UtrillaJC** [comment]
Primera versión del commit: https://github.com/decide-ganimedes-censo/decide-ganimedes-censo/commit/36539071338d7e429d8ab8b5205912a743d107e2

**Comment by UtrillaJC** [comment]
El script ya esta terminado, a la espera de que @Iriabow revise su funcionamiento

**Comment by Iriabow** [comment]
El script de @UtrillaJC  ha sido probado desde Manjaro y funciona perfectamente, además de ser intuitivo y fácil de usar.

**Comment by UtrillaJC** [comment]
Se han incorporado el script dockerManager.sh y readme.txt en la rama master. Pendiente de que @Iriabow incluir en el siguiente Pull-Request.
