### ISSUE TITLE
Restringir el censo para que sea antes de la votación

### ISSUE THREAD

**Issue by UtrillaJC** [decide-ganimedes-censo/decide-ganimedes-censo#17]
Hablando con @Iriabow en en issue #14, hemos acordado modificar el funcionamiento del censado actual porque no tiene sentido que sea durante la votación, sino antes del comienzo de la votación.

**Comment by Iriabow** [comment]
Debe hacerse así con todas las funciones en view que añaden usuarios a un censo.
