### ISSUE TITLE
Visualización de los usuarios de un censo

### ISSUE THREAD

**Issue by chainwarden16** [decide-ganimedes-censo/decide-ganimedes-censo#18]
En el listado de censos, será necesario mostrar los usuarios asociados al censo de una votación.

Los datos a mostrar, insertados en una tabla, serán: nombre, apellidos, edad, sexo, ciudad y fecha de nacimiento. Estos datos se mostrarán en una vista diferente. Actualmente el botón asociado a dicha funcionalidad está en la vista, pero al hacer clic en él no realizará ninguna acción.

**Comment by Iriabow** [comment]
¿Estás poniendo las referencias al issue que corresponde en los commits? Además tienes que controlar el estado de las issues en el tablero kanban.

**Comment by Iriabow** [comment]
**Tendrías que realizar los siguientes cambios:**
* Cambiar lo del listado para que no incluya la template "admin" en el template, tampoc debe aparecer en la url.
* En las templates usar el name de las urls.
* En el listado de censos, aparece "Eliminar" en lugar de "Delete"
* Añadir placeholders.
* Mejorar la legibilidad y el css.
* En el listado en lugar del botón "VIEW VOTERS" pon el nombre del usuario como enlace.
* Al lado de los botones de "ADD CENSUS WITH FILTERS" y "ADD CUSTOM CENSUS", añade los botones "IMPORT ALL" y "EXPORT ALL".
* Quitar la barra de búsqueda.

**Comment by chainwarden16** [comment]
Lo del listado de censos se debe a que uso el bloque trans para traducir el título de esa sección de la tabla, según el idioma que se tenga elegido. Yo estoy trabajando con Decide en inglés y me aparece "Delete".

**Comment by UtrillaJC** [comment]
![image](https://user-images.githubusercontent.com/9322398/50761070-bcce1800-1269-11e9-8b8e-acee389e454d.png)

Al aplicar el filtro addCustomCensus, te redirige listCensus (eso está bien), pero muestra 3 líneas exactamente iguales y no queda claro que es cada uno. Si pulsas en cada uno de los botones ViewVoters, nos redirigen al mismo sitio y mostrando los mismos datos. 

Puedes optar por **dos soluciones** que se me acaban de ocurrir: 
- **Opción 1 (descartada)**: a la hora de hacer la query, hacer un distinct para que sólo muestre una columna y el botón ViewVoters. 
**Problema**: si la vista (como concepto de DP) lista los censos, la vista no estaría cumpliendo su función (de hecho no estás viendo los censos) y sobraría.

- Opción 2: Consta de dos modificaciones:
**Modificación 2.1 - Columna Voting**: en lugar de mostrar el id (que no es para nada intuitivo) muestra el nombre de la votación correspondiente o si quieres mantener el id (que nos facilitaría mucho a la hora de mostrarselo al profesor), muestra el nombre de la votación seguida del id de la votación, en plan:

Votación 1 - 1, Votación 2 - 2
Votación 1 (1), Votación 2 (2)

**Modificación 2.2 - Columna Voters**: muy parecida a la modificación 2.1, pero cambiando el botón por un link con el nombre del votante.

Con esto, la vista ya tendría sentido.

**Comment by UtrillaJC** [comment]
![image](https://user-images.githubusercontent.com/9322398/50761369-8218af80-126a-11e9-9960-68795225bee7.png)

Si no hay votaciones, en lugar de mostrar las columnas vacías, sería mejor que apareciese un mensaje diciendo: "No hay censos disponibles" o algo por el estilo.

**Comment by UtrillaJC** [comment]
![image](https://user-images.githubusercontent.com/9322398/50762459-4df2be00-126d-11e9-9b26-56b5e44f160e.png)

Al hacer clic sobre el bóton ViewVoters...

![image](https://user-images.githubusercontent.com/9322398/50762506-6b278c80-126d-11e9-93c1-31cf985a1a04.png)

Aparece Mostrar Censo, cuando debería aparecer Mostrar votante. Además, no tiene sentido que en la fecha de nacimiento aparezca la hora a la que nació, por lo que deberías de modificar el patrón.

**Comment by chainwarden16** [comment]
¿Se podría quitar la hora de la fecha de nacimiento a la hora de crear un usuario? No tiene mucho sentido que se ponga eso también; con el día, el mes y el año debería ser suficiente.

**Comment by Iriabow** [comment]
Lo de quitarlo de la creación del usuario, lo he comentado por el grupo de coordinación a ver que me dicen, en principio es cosa de autenticación.
