### ISSUE TITLE
Exportación de censo en archivo csv

### ISSUE THREAD

**Issue by chainwarden16** [decide-ganimedes-censo/decide-ganimedes-censo#2]
Para facilitar la exportación de censos, podría añadirse funcionalidad para leer un censo guardado en base de datos y parsearlo para guardarlo finalmente en un archivo csv. 

Para facilitar la importación del censo en el futuro, deberá respetarse el formato de lectura de archivos implementado.

**Comment by UtrillaJC** [comment]
Hasta que @chainwarden16 implemente el template de la página principal he creado un botón temporal en addCustomCensus que llama a la URL http://localhost:8000/census/exportCensus .

Pendiente de qué @Iriabow verifique su correcto funcionamiento.

**Comment by Iriabow** [comment]
Funciona correctamente.
