### ISSUE TITLE
Vista para creación de censos con filtros simples

### ISSUE THREAD

**Issue by chainwarden16** [decide-ganimedes-censo/decide-ganimedes-censo#21]
Se necesita implementar la vista para crear censos mediante filtros simples. Esto es: filtro por ciudad, por sexo, por edad y por último uno que permita añadir todos los usuarios del sistema.

**Comment by Iriabow** [comment]
**Tendría que aplicar los siguientes cambios**
* Has los formularios con GET, y añade los names adeacuados a los imputs.
* Ten cuidado con los selects, deben tener siempre un valor por defecto, que no debe ser valido (es decir no se debe realizar ninguna operación con dicho valor, pero tampo debe dar error, puede que haya que modificar algo en la implementación de los filtros).
* Añade el filtado por edad, "filterAllByAge", tiene los siguientes parámetros: voting_id, younger y older. Younger y older son simplemente integers.

**Comment by chainwarden16** [comment]
Para el filtro de edad, ¿pongo una edad mínima en cada uno de los parámetros? (Veo absurdo censar personas que tienen 0 años y cosas así, y además de la imposibilidad de que haya alguien con -1 años.)

**Comment by chainwarden16** [comment]
Es necesario añadir la función addAllByAge en views.py para que la página de filtros simples pueda abrirse.

**Comment by Iriabow** [comment]
Ya tienes addAllByAge añadelos a la página de filtros simples.

**Comment by UtrillaJC** [comment]
![image](https://user-images.githubusercontent.com/9322398/50761909-db351300-126b-11e9-8003-2e0a6314e3ee.png)

Para cada input de todos los formularios, debes incluir un label encima de él, y no debajo tal y como aparece en "Create census with users from this city".

Podéis fijaros cómo está implementado en addCustomCensus #14 

![image](https://user-images.githubusercontent.com/9322398/50761990-0c154800-126c-11e9-88d6-8f37a086746d.png)
