### ISSUE TITLE
Vista para exportar censo

### ISSUE THREAD

**Issue by chainwarden16** [decide-ganimedes-censo/decide-ganimedes-censo#22]
Se necesita una vista para cuando el usuario realice una exportación de censo de todos los usuarios del sistema.

**Comment by Iriabow** [comment]
Puedes fijarte, en el formulario que está provisionalmente al final del template add_custom_census.html hecho por @UtrillaJC .

**Comment by UtrillaJC** [comment]
A la hora de hacer clic en Export all...

![image](https://user-images.githubusercontent.com/9322398/50761471-c310c400-126a-11e9-9ee4-5ea15872e44e.png)

...este te redirige a la vista Exportar CSV. Si vas a Exportar todos los censos de la base de datos, no tiene sentido tener una vista para exportar todo el CSV. Lo lógico sería que al pulsar en Botón Export all en la vista anterior directamente te preguntase donde quieres que guardes el fichero.

![image](https://user-images.githubusercontent.com/9322398/50761590-0d924080-126b-11e9-877a-dbe6888e1f78.png)

Donde si tiene sentido es el #23 

Además, la maquetación CSS está mal: habría que centrarla y añadir la internacionalización.

**Comment by chainwarden16** [comment]
He invalidado este issue, puesto que se va a retirar la vista a la hora de exportar censos.
