### ISSUE TITLE
Vista para importar censo

### ISSUE THREAD

**Issue by chainwarden16** [decide-ganimedes-censo/decide-ganimedes-censo#23]
Es necesario implementar una vista para soportar la acción de importar censos al sistema.

**Comment by UtrillaJC** [comment]
![image](https://user-images.githubusercontent.com/9322398/50761743-74175e80-126b-11e9-9ddb-62d3dcc38b00.png)

Falta por corregir la maquetación CSS y añadir la internacionalización.
