### ISSUE TITLE
Error al desplegar docker con el script bash

### ISSUE THREAD

**Issue by Iriabow** [decide-ganimedes-censo/decide-ganimedes-censo#26]
Se ha reportado por parte de autenticación el siguiente error al desplegar la aplicación sobre docker en el issue:
* [Error al desplegar la aplicación en docker](https://github.com/decide-ganimedes/decide-ganimedes/issues/63)

**Comment by UtrillaJC** [comment]
Respecto a los errores que han salido, no ha sido por el script. En determinadas máquinas Linux (no en todas) aparecen errores en el despliegue debido a que el fichero docker-compose.yml se descarga determinadas versiones que causan conflictos con el resto de contenedores.

**Sistema operativo de pruebas**: [Ubuntu Bionic Reaver 18.04 [x64]](http://releases.ubuntu.com/18.04/ubuntu-18.04.1-desktop-amd64.iso) 

Desconozco porque ocurre, ya que a mi me pasó y lo solucioné editando el docker-compose.yml para que descargase una versión concreta y se solucionó, pero por diversos motivos, tuve que formatear mi equipo y al desplegarlo con la configuración del docker-compose.yml por defecto volvió a funcionar. No se si estará relacionado con las dependencias del sistema operativo local. 

#### Visualización de errores de los contenedores

 * **Opción 1**: mediante el comando sudo docker-compose logs
 * **Opción 2**: opción 7 con el demonio de Docker ACTIVO en el script dockerManager.sh

![image](https://user-images.githubusercontent.com/9322398/50784727-cc238480-12ae-11e9-90f3-d17ef01c6cae.png)

#### Solución

Tendréis que indicar manualmente en el docker-compose.yml qué versión de imagen tenéis que descargarse para que deje de dar conflicto. Eso se ve fácilmente observando los logs que devuelven los contenedores.

Buscaremos una imágen en **Docker Hub** que solucione esta incidencia. En este caso, se soluciona escribiendo la versión de **[PostgreSQL 11.1-alpine](https://hub.docker.com/_/postgres)** de **[Docker Hub](https://hub.docker.com/)** en el fichero docker-compose.yml

![image](https://user-images.githubusercontent.com/9322398/50785278-69cb8380-12b0-11e9-985c-3d429d1a2a9b.png)
