### ISSUE TITLE
Testing del censado por rango de edad.

### ISSUE THREAD

**Issue by Iriabow** [decide-ganimedes-censo/decide-ganimedes-censo#36]
Se debe testear la funcionalidad que añade miembros al censo de una votación a partir de un rango de edad correspondiente a la siguiente issue:

[Opción de añadir usuarios al censo según la edad.](https://github.com/decide-ganimedes-censo/decide-ganimedes-censo/issues/20)

**Comment by UtrillaJC** [comment]
Fue un error temporal debido a unos cambios temporales que ni siqueran estaban subidos. Procedo a cerrar el issue.
La issue válida es la #37
