### ISSUE TITLE
Adaptar los antiguos tests de funcionalidad implementados

### ISSUE THREAD

**Issue by Iriabow** [decide-ganimedes-censo/decide-ganimedes-censo#8]
Habrá que actualizar los test debido a los cambios que se realicen a lo largo del desarrollo de la aplicación (Ej: cambios en autenticación de usuarios, ...).

Está relacionado con el issue #7

**Comment by davidromesp** [comment]
7da7ec654f6c9d8f2325aedf27515cfe50dac176
Con este commit, ya funcionan todos los tests de census

**Comment by Iriabow** [comment]
Todo en orden, paso el issue a pendiente de pull request.
