### ISSUE TITLE
Controlar la creación de censos con datos no existentes en la base de datos

### ISSUE THREAD

**Issue by UtrillaJC** [decide-ganimedes-censo/decide-ganimedes-censo#9]
Hay que controlar que no se pueda crear una votación con un usuario que no existe y viceversa a nivel de servicios. A continuación se muestra un ejemplo con un votingId y con un voterId que no existen:

![imagen1](https://user-images.githubusercontent.com/9322398/50035456-7850b300-0002-11e9-9e48-b6009f1a4aef.jpeg)

![imagen2](https://user-images.githubusercontent.com/9322398/50035464-7d156700-0002-11e9-89e8-7107ea98fa02.jpeg)

**Comment by davidromesp** [comment]
En este momento, los censos con filtros automáticos no permiten que se puedan crear censos para votaciones inexistentes.
Hay que investigar cómo controlarlo en la creación básica.
